cart page
VOID0304/instamart pull request #20
Opened 2024-01-22 16:38 UTC by sowjanya1308

2024-01-22 16:50 UTC, Geswar003 approved these changes

2024-01-23 04:19 UTC, rahul181203 requested changes

2024-01-23 04:19 UTC, rahul181203 commented on client/src/components/cart components/liked_cards.tsx
> +                    <h2 className="font-bold text-lg mb-2">Hershy's Syrup: 623gms</h2>
Hershy's syrup: 623gms need to be in jsx format

2024-01-23 04:19 UTC, rahul181203 commented on client/src/components/cart components/liked_cards.tsx
> +                    <h2 className="font-bold text-lg mb-2">Hershy's Syrup: 623gms</h2>
same issue as above

2024-01-23 04:20 UTC, rahul181203 requested changes
resolve the issues which was commented

2024-01-23 09:31 UTC, rahul181203 approved these changes

2024-01-23 09:35 UTC, Gomukha30 approved these changes

2024-01-23 09:35 UTC, merged